# -*- coding: utf-8 -*-
"""ascii_video

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQTfYQtLDhMmmqj6yoj7GhhXcQ9UWZ8I
"""

import cv2
#used to take input video which will later be converted to ascii

from PIL import Image, ImageDraw, ImageFont
import numpy as np
import math

# Character set for mapping brightness
chars = "$@B%8&WM#*oahkbdpqwmZ0@QLCJUYXzevunxjft/\\/0)1470]?-_+~<>i!11;:,\"^. "[::-1]
charArray = list(chars)#converting above str to a list
charLength = len(charArray)
interval = charLength / 256

# above block mai its converting character ka str to list, storing its length and mapping it to fit to the 0 to 255 range
# which here is 0 to 70 as there are only 70 total characters so 1 to 1 mapping isnt possible and if woh karege toh video will be very slow

# Configuration
scaleFactor = 0.09 #downsampling of webcam feed, reduces the img to 9% of its original size
oneCharWidth = 10
oneCharHeight = 18

# Load font properly (ensure arial.ttf exists or use default)
try:
    fnt = ImageFont.truetype('arial.ttf', 15)
except:
    fnt = ImageFont.load_default()

video_capture = cv2.VideoCapture(0)
#this line takes input from your default webcam of your pc

def getChar(inputInt):
    return charArray[math.floor(inputInt * interval)]

while True:
    ret, frame = video_capture.read()
    if not ret:
        break

    # 1. Convert BGR to RGB kyuki Pillow uses RGB
    color_converted = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    im = Image.fromarray(color_converted)

    width, height = im.size

    # 2. Resize for ASCII processing

    im = im.resize((int(scaleFactor * width), int(scaleFactor * height * (oneCharWidth / oneCharHeight))), Image.NEAREST)

    width, height = im.size
    pix = im.load()

    # 3. Create a blank canvas for the text
    outputImage = Image.new('RGB', (oneCharWidth * width, oneCharHeight * height), color=(0, 0, 0))
    d = ImageDraw.Draw(outputImage)

    for i in range(height):
        for j in range(width):
            r, g, b = pix[j, i]
            # Calculate brightness
            brightness = int(r/3 + g/3 + b/3)
            char = getChar(brightness)
            # Draw the character at the specific grid location
            d.text((j * oneCharWidth, i * oneCharHeight), char, font=fnt, fill=(255, 255, 255))

    # 4. Convert back to OpenCV format (BGR) for display
    outputImage_cv = np.array(outputImage)
    outputImage_cv = cv2.cvtColor(outputImage_cv, cv2.COLOR_RGB2BGR)

    cv2.imshow('ASCII Output', outputImage_cv)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()